[package]
name = "gera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = "4.5.1"
ethers = "2.0.13"
hex = "0.4.3"
rand = "0.8.5"
